### ISSUE TITLE
Ajouter de nouveaux indicateurs à la page stats

### ISSUE THREAD

**Issue by florianpanchout** [datagir/datagir-site#100]
- [x] Taux d'interaction
- [ ] Format tableau (en + du graph)

**Comment by Clem-mrtn** [comment]
Suite au séminaire on s'était noté de suivre de nouveaux indicateurs quantis et de les faire apparaître sous forme de dashboard (en privé au démarrage) pour mieux suivre les évènements 

**Liste des indicateurs à monitorer pour chaque produit :** 

- Nb de visiteurs uniques
- Nb de simulateurs terminées
- Nb de session avec au - 1 interaction
- Tps moyen / session
- nb d'intégrations

**Comment by florianpanchout** [comment]
C'est en ligne
