### ISSUE TITLE
Bug affichage page statistiques 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/datagir-site#110]
La [page stat](https://datagir.ademe.fr/stats/) du site Datagir ne s'affiche plus correctement (même en navigation privée), on a une page blanche 
<img width="1466" alt="Capture d’écran 2023-02-20 à 14 27 35" src="https://user-images.githubusercontent.com/76995768/220121493-f61f023a-fdb2-4fba-8f95-bbec536dbdf3.png">

**Comment by florianpanchout** [comment]
En lien avec https://github.com/datagir/nosgestesclimat-site/pull/849

Le plus simple serait de retirer NGC de la liste. Le plus complexe serait de reprendre la solution mise en place par NGC.

J'aurais tendance à aller au plus simple pour une page d'un site qui va forcement changer (ou disparaitre) et qui attire 10 visiteurs par semaine

**Comment by Clem-mrtn** [comment]
Yes ok pour retirer les stats de NGC pour réparer la page 👍

**Comment by florianpanchout** [comment]
C'est réparé : https://datagir.ademe.fr/stats/
