### ISSUE TITLE
Bug formulaire contact 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/datagir-site#52]
Lorsqu'on renseigne le formulaire contact et qu'on clique sur envoyer on est redirigé sur la page 404 
Puis ça se  réactualise automatiquement sur la homepage

**Comment by florianpanchout** [comment]
C'est corrigé. Sur quel mail voulez vous forwarder les messages ?

**Comment by florianpanchout** [comment]
C'est fait !

**Comment by florianpanchout** [comment]
(Je m'occupe de mettre en page la page de confirmation demain matin)

**Comment by florianpanchout** [comment]
Fait

**Comment by florianpanchout** [comment]
@martinregner @Clem-mrtn Les sujets possibles du formulaire de contact ("Nos simulateurs" et "Nos jeux de données") n'ont jamais été discuté/réfléchi. Vous souhaitez peut être autre chose non ?

**Comment by martinregner** [comment]
C'est les deux grands points de notre offre.
Tu peux au moins ajouter un "Autre sujet", et si on a que des "autres" on trouvera une nouvelle catégorie ?

**Comment by florianpanchout** [comment]
Si on ne fait aucun tri en amont et que tous les messages arrivent au même endroit, est ce que ça a du sens de laisser ce select ?

**Comment by martinregner** [comment]
Bonne question. Un champ libre "Objet de votre message" par ex. est peut-être tout aussi bien.
@Clem-mrtn tu en penses quoi ?

**Comment by Clem-mrtn** [comment]
Ce select c'est bien ce qui s'affichera en **objet du mail ?**
Si c'est le cas c'est quand même bien de le laisser, ça nous permet de qualifier les demandes plus facilement sur la boîte de Datagir !

=> Et du coup oui peut-être envisager un troisième champs libre pour qualifier davantage la demande  : 

_Select Autre 
-> Apparition d'un champs texte en dessous dans le formulaire " Objet de votre message"_

**Comment by florianpanchout** [comment]
Nope, il ne s'affichera pas en objet.

D'ailleurs, ce qu'il est possible de faire avec un formulaire via Netlify : 

- Envoyer un mail à une (ou plusieurs) adresse avec comme objet : Form submission from contact form: Nom
- Envoyer vers un service type Airtable ou autre (du moment que ça accepte une requête externe). J'imagine que votre outil crm du moment est compatible :)
- Envoyer vers un channel slack

Il y a quelque chose qui vous intéresse la dedans ?

**Comment by martinregner** [comment]
cf. https://github.com/datagir/teletravail/issues/6
