### ISSUE TITLE
Section " Données personnelles et gestion des cookies"

### ISSUE THREAD

**Issue by martinregner** [datagir/datagir-site#55]
J'aime bien ce qu'ils ont fait chez Santé Psy, ça explique bien pourquoi pas de bandeau cookie 
https://santepsy.etudiant.gouv.fr/donnees-personnelles-et-gestion-des-cookies

Pour notre "données personnelles" et "gestion des cookies" du bas de page (à fusionner ?) on pourrait avoir une page de ce genre ?
Ca permettrait de répondre à cette problématique pour tous les calculateurs à la fois non ? cf. https://github.com/datagir/nosgestesclimat-site/issues/233

**Comment by florianpanchout** [comment]
C'est fait : https://datagir.ademe.fr/cookies

J'ai modifié le wording pour inclure l'ensemble des simulateurs.

**Comment by martinregner** [comment]
Cool ! 👍 

**1. Remarques de wording :**

_C’est vrai, vous n’avez pas eu à cliquer sur un bloc qui recouvre la moitié de la page pour dire que vous êtes d’accord avec le dépôt de cookies._ ~~**même si vous ne savez pas ce que ça veut dire !**~~

_Rien d’exceptionnel, pas de passe-droit ~~lié à un .gouv.fr~~ **en tant que service public**. Nous respectons simplement la loi, qui dit que certains outils de suivi d’audience, correctement configurés pour respecter la vie privée, sont exemptés d’autorisation préalable._

**2. Liens du bas de page**

Possible de renvoyer _**données personnelles**_ et _**gestion des cookies**_ vers cette page ?

**Comment by florianpanchout** [comment]
C'est corrigé
