### ISSUE TITLE
Stats > Mettre un espace séparateur de millier

### ISSUE THREAD

**Issue by martinregner** [datagir/datagir-site#60]

**Comment by florianpanchout** [comment]
Fait

**Comment by martinregner** [comment]
Possible aussi sur le graphe et les encarts en bas ?

**Comment by florianpanchout** [comment]
Possible et fait :) 

J'en ai profité pour revoir l'affichage des tooltips sur le graph

**Comment by martinregner** [comment]
Génial ! 🤩

**Comment by martinregner** [comment]
Je crois que j'ai trouvé le dernier séparateur de millier à ajouter, pour l'axe des ordonnées 😉

**Comment by florianpanchout** [comment]
C'est fait :)

Maintenant que j’ai formaté tous les milliers vous avez interêt à bizdev un peu pour que ça se voit !
