### ISSUE TITLE
Stats > Nb de simulations

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/datagir-site#64]
Une fois paramétrer sur Matomo afficher le nombre de simulations / simulateurs

**Comment by martinregner** [comment]
Commencer par NGC, ex.
![image](https://user-images.githubusercontent.com/46482115/141762824-575181b6-600d-4544-898e-f2978000f998.png)

**Comment by Clem-mrtn** [comment]
Notamment sur NGC

**Comment by florianpanchout** [comment]
Peut être profiter de ce ticket pour repenser plus largement la page stats ? (affichage des appels à l'api MIT notamment)

**Comment by florianpanchout** [comment]
Done via https://github.com/datagir/datagir-site/issues/73

**Comment by martinregner** [comment]
Top !!
Plutôt que "forks du code" peut-être pas ultra parlant, que penses-tu de "reprises du code" ?

**Comment by florianpanchout** [comment]
C'est corrigé

**Comment by Clem-mrtn** [comment]
Quelques petites réflexions : 

![image](https://user-images.githubusercontent.com/76995768/148415069-c09a10f4-07ab-4528-ada7-88d5d38d28e5.png)

- On spécifie "En chiffres" mais ce qu'on donne au début ce sont aussi des chiffres avec les graphiques. Est-ce qu'on mettrait pas simplement  ces chiffres avec ceux du graphe ? Ou alors tu as fait le test @florianpanchout et ça fait trop ? 
Si on veut aérer et se garder une rubrique à part, p-t la renommer => Nombres de simulations et déclinaisons Nos Gestes Climat ?

- On peut peut-être simplement écrire Gestes et pas GEStes... C'est débat vieux comme le monde 😅 Mais ça fait un peu lourd moi je trouve et on l'utilise jamais à l'écrit

**Comment by Clem-mrtn** [comment]
Ah oui et question quand on charge la page on a l'appel à l'API qui s'affiche en premier et ensuite la totalite 
![image](https://user-images.githubusercontent.com/76995768/148416482-270a807c-77da-4449-9b6e-78a6a182cec3.png)

C'est parce que le graphique met du temps à s'afficher j'imagine ?

**Comment by florianpanchout** [comment]
> On spécifie "En chiffres" mais ce qu'on donne au début ce sont aussi des chiffres avec les graphiques. Est-ce qu'on mettrait pas simplement ces chiffres avec ceux du graphe ? Ou alors tu as fait le test @florianpanchout et ça fait trop ?

C'était pour faire comme la section d'en dessous "Datagir en chiffre", mais effectivement ça ne marche peut être pas ici. J'ai modifié pour qu'il s'affiche à la place du nombre d'affichage d'iframe NGC (qui de toute façon ne fonctionne pas correctement pour NGC). Pas la place pour le nombre de forks du coup. Je ne suis pas sur que ce chiffre avait beaucoup de sens de toute façon.

Pour `GES` => `Ges` ça me va de changer mais il faut le faire partout sur le site alors

> C'est parce que le graphique met du temps à s'afficher j'imagine ?

Oui c'est pour ça que j'ai mis un petit logo animé en attendant. Mais il n'y en avait pas pour les autres rubriques (alors qu'elles dépendent des mêmes données). C'est corrigé
