### ISSUE TITLE
Modifier les textes de partage /simulateur 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/datagir-site#68]
Modification des textes de partage en fonction des réseaux sociaux / simulateurs

**Comment by martinregner** [comment]
@Clem-mrtn j'ai fait un doc trame ici : https://cloud.datagir.com/index.php/f/5759

**Comment by martinregner** [comment]
@Clem-mrtn @florianpanchout j'ai tout revu et rempli ^^

Pour le tutoiement / vouvoiement je propose : 
- **Facebook, Twitter, LinkedIn** : c'est un post collectif la plupart du temps (plutôt qu'un MP) --> _vous_
- **WhatsApp** : forte probabilité que ce soit à une seule personne --> _tu_
- **Mail** : _vous_ pour le partage du simulateur (c'était comme ça, ça me paraissait pas mal... on envoie potentiellement à plusieurs contact / des contacts qu'on connait peu), _tu_ pour le partage du résultat

Toute proposition bienvenue bien sûr ! :)

**Comment by Clem-mrtn** [comment]
Je viens de reparcourir, c'est tout bon pour moi ! :) 
J'ai juste légèrement modifié le texte pour que ce soit moins lourd sur le partage de QFDMD sur FB, Twitter & Whatsapp 

Ok pour intégration 👍

**Comment by florianpanchout** [comment]
Ah oui, il y avait un problème sur MIT. C'est corrigé

(les autres sont bon normalement)

**Comment by Clem-mrtn** [comment]
Trop bizarre je ne vois rien de changer sur aucun des simulateurs ? même MIT

**Comment by florianpanchout** [comment]
(je réalise maintenant que l'information importante n'est pas dans le titre mais dans la description. Je corrige ça)
