### ISSUE TITLE
Ajouter QFDMD dans la liste des simulateurs

### ISSUE THREAD

**Issue by martinregner** [datagir/datagir-site#71]
Page .../apps/ :

Texte en intro : 
`Trouvez où jeter tout type de déchet près de chez vous, ce qu'il va devenir et comment l'éviter.`

Réutilisateurs :
ADEME ; https://agirpourlatransition.ademe.fr/particuliers/maison/faire-dechets

**Comment by florianpanchout** [comment]
Done : https://datagir.ademe.fr/apps/que-faire-de-mes-dechets/

**Comment by martinregner** [comment]
Parfait ! :)

Sur l'accueil, peut-être passer le "En savoir +" en rouge ? Le bouton reprend la couleur qui est ensuite sur la page non ?

![image](https://user-images.githubusercontent.com/46482115/135877717-e086a75a-fbb5-4538-874d-dd125eb7d32a.png)

**Comment by florianpanchout** [comment]
Nope la couleur est liée au secteur (alimentation, transport ou logement). Ici pas de secteur donc vert Datagir par défaut

**Comment by martinregner** [comment]
Yes c'est vrai ! 👍
