### ISSUE TITLE
Améliorer page stats

### ISSUE THREAD

**Issue by florianpanchout** [datagir/datagir-site#73]
- [x] Ajouter un indicateur de chargement
- [x] Corriger le bug lorsque l'on vide l'input temps
- [x] Corriger le bug lorsque l'on filtre par nouveaux réutilisateurs

**Comment by florianpanchout** [comment]
J'ai aussi ajouté un graph avec les appels à l'api MIT.

**Comment by florianpanchout** [comment]
Et maintenant le nombre de simulations terminées sur NGC.

@laem J'ai pris le nombre de visites avec l'action `A terminé la simulation`. 

Vu que le tracking ne remonte pas jusqu'au lancement du simulateur, je suis parti du principe que le pourcentage de complétion (29.18%) est resté le même et ai donc estimé le nombre de simulations terminées à partir du nombre de visites pre-matomo (109689).

J'ai aussi ajouté en dur le nombre de fork du repo ngc

**Comment by martinregner** [comment]
> Vu que le tracking ne remonte pas jusqu'au lancement du simulateur, je suis parti du principe que le pourcentage de complétion (29.18%) est resté le même et ai donc estimé le nombre de simulations terminées à partir du nombre de visites pre-matomo (109689).

Pour bien comprendre : le 29.18% sert uniquement pour l'historique avant tracking `A terminé la simulation` (109689) et ensuite c'est les vrai chiffres de tracking qui s'ajoutent à cet historique c'est ça ?

---
Tu as mis un sélecteur, limité à `12` désormais. Je t'avoue que c'est un peu limitant pour regarder l'évolution sur les 30 jours d'un mois donné par exemple. Le champs libre c'était gênant ?

**Comment by florianpanchout** [comment]
> Pour bien comprendre : le 29.18% sert uniquement pour l'historique avant tracking A terminé la simulation (109689) et ensuite c'est les vrai chiffres de tracking qui s'ajoutent à cet historique c'est ça ?

Yes c'est bien ça

> Tu as mis un sélecteur, limité à 12 désormais. Je t'avoue que c'est un peu limitant pour regarder l'évolution sur les 30 jours d'un mois donné par exemple. Le champs libre c'était gênant ?

A non pas du tout. Je ne voyais juste pas d'utilité statistique à afficher 30 jours plutôt que 4 semaines. Le select me permet de debugger simplement quelques trucs, mais je peux mettre un select jusqu'à 30

**Comment by martinregner** [comment]
OK. Volontiers pour un select jusqu'à 30 alors :)

**Comment by florianpanchout** [comment]
Done !
