### ISSUE TITLE
Les nouveaux réutilisateurs n'apparaissent plus sur le site

### ISSUE THREAD

**Issue by martinregner** [datagir/datagir-site#76]
Par ex. celles-ci dessous ne sont pas intégrées

https://github.com/datagir/datagir-site/commit/36463d38fa7452d56a6b40ecf818e358e693b8dd#diff-e8755fc89f83dd0ffbac62a67d644165517354a9e15f617710e42e5fa7455506

https://github.com/datagir/datagir-site/commit/ee75f4b7900c9693915c5d0718386bfc7dd89e46#diff-e8755fc89f83dd0ffbac62a67d644165517354a9e15f617710e42e5fa7455506

**Comment by florianpanchout** [comment]
C'est corrigé !

**Comment by martinregner** [comment]
@florianpanchout ça remarche pas avec 2 lignes que j'ai ajouté ce matin...
Il y a qqc que je fais mal ? 🤔

**Comment by florianpanchout** [comment]
`grand-poitier.jgp` à la place de `grand-poitier.jpg`

C'est corrigé :)
