### ISSUE TITLE
Ajouter les réutilisateurs du code source 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/datagir-site#77]
Wording : Les Déclinaisons

**Comment by florianpanchout** [comment]
C'est fait. J'ai ajouté un exemple sur NGC (https://datagir.ademe.fr/apps/nos-gestes-climat/). Ils sont listés dans le markdown (https://github.com/datagir/datagir-site/blob/master/content/applications/nos-gestes-climat/index.md) sous l'attribut `forks`.

Vous pouvez aussi ajouter cet attribut aux autres simulateurs si besoin

**Comment by Clem-mrtn** [comment]
Top ! 
On s'était pas listé les réutilisateurs d'API aussi ?

**Comment by florianpanchout** [comment]
Est ce qu'on en a d'autre que Fnac-Darty ? J'ai l'impression qu'ajouter leur logo dans les réutilisateurs suffirait pour l'instant non ?

**Comment by Clem-mrtn** [comment]
Tout à fait 
Non pas d'autres pour l'instant
