### ISSUE TITLE
Ajouter les licences dans chaque repos

### ISSUE THREAD

**Issue by florianpanchout** [datagir/datagir-site#81]

**Comment by florianpanchout** [comment]
@martinregner c'est quoi les licenses de nos simulateurs ?

**Comment by martinregner** [comment]
https://github.com/datagir/nosgestesclimat-site/blob/master/LICENSE sauf erreur.

@laem c'est toujours bon ? Je vois qu'ici tu avais ajouté ton nom au copyright https://github.com/datagir/nosgestesclimat/blob/master/LICENSE 😉

**Comment by florianpanchout** [comment]
@laem

**Comment by Clem-mrtn** [comment]
=> Demander à Ishan ou juriste beta.gouv

**Comment by florianpanchout** [comment]
On a eu un retour ?

**Comment by laem** [comment]
Quelle est la question précisément ? Quelle licence choisir ? C'est ici que les possibilités sont listées : https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000034502557

Par défaut, c'est du MIT ou assimilé. Je n'arrive plus à trouver la référence qui dit que l'utilisation d'une licence contaminante doit être justifiée. 

Mais de toutes façon dans notre cas, utiliser une licence contaminante est impossible pour les iframes.

**Comment by florianpanchout** [comment]
Apparemment on était sensé demander à Ishan (https://github.com/datagir/datagir-site/issues/81#issuecomment-1032395188)

**Comment by martinregner** [comment]
C'est fait, cf. fil Mattermost du 8/02.
Pas réellement de réponse, le ping au référent logiciels libres à beta n'a pas été suivi d'effet.

Je refais un fil de conversation avec lui.

**Comment by florianpanchout** [comment]
Je relance cette issue. J'ai besoin d'une réponse pour Verdir ma Flotte

**Comment by laem** [comment]
Quelle est la question ?

**Comment by florianpanchout** [comment]
Quelle est la licence que l'on est sensé utiliser pour l'ensemble de nos sites. Apparemment on était en attente de la réponse d'un juriste de beta. Moi ça me va d'utiliser MIT

**Comment by florianpanchout** [comment]
Licence MIT ajoutée sur tous les repo actifs
