### ISSUE TITLE
Chiffres NGC simulations : quelle période ?

### ISSUE THREAD

**Issue by laem** [datagir/datagir-site#83]
@florianpanchout j'ai du mal à interpréter la requête https://github.com/datagir/datagir-site/blob/84d9707485b5951b3e3b488d357160bbcd159b2f/src/utils/matomo.js#L78

J'ai remarqué que le décompte ne change pas avec le sélecteur en haut à droite de la page /stats.
Ce serait bien de mettre un sous-titre explicitant la période, comme ici. J'ai l'impression que les chiffres ne reflètent pas l'année 

![image](https://user-images.githubusercontent.com/1177762/148390404-fcd808b7-1eda-4aa8-8a6b-3453318615ca.png)

**Comment by florianpanchout** [comment]
Le sélecteur ne vaut que pour le graph accolé. 

La requête renvoie pour chaque évènement les totaux des 6000 derniers jours. La dedans je pioche le nombre de visites qui ont déclenché l'évènement "A terminé la simulation".

J'ai modifié le label pour "simulations terminées depuis le lancement"
