### ISSUE TITLE
Visuels Datagir 

### ISSUE THREAD

**Issue by Clem-mrtn** [datagir/datagir-site#86]
- Infographie sur nos outils pour faciliter la communication sur les RS par ex ou lors d'event 
- Visuels pour Kakémono Datagir ADEME pour le Grand évènement : dimensions 80x200

**Comment by Clem-mrtn** [comment]
Pistes de réflexions du Kakémono : 
- Logo + slogan ?
- QR code (vers tous les outils ? ou vers NGC ?) 
- Vignettes simulateurs ?
- Infographie ?

**Comment by Clem-mrtn** [comment]
Brief Créa 

- Logos Datagir + ADEME + RF
- slogan "Apporter l'information environnementale au plus près des citoyens"
- Visuels : les logos des simulateurs (MIT, QFDMD, MCCO2, MFLDS)

**Comment by florianpanchout** [comment]
Une première version : 
![Screenshot 2022-03-04 at 11 25 42](https://user-images.githubusercontent.com/8115933/156746271-5925c3da-cf05-4e20-9864-6bf304e47f1f.png)

**Comment by Clem-mrtn** [comment]
C'est cool ! La tablette c'est très sympa 
Est-ce qu'on pourrait essayer une version où on a : 
- Le logo Datagir un peu plus petit 
- Une petit phrase d'intro sous la tablette, avant les simulateurs **" Découvrez nos outils de sensibilisation"**
- Remplacer le sreenshot de la vieille version de MCCO2 par la nouvelle (le figma par exemple)
- Juste pour essayer, supprimer le screen Agribalyse et ne mettre que les 4 autres outils

**Comment by florianpanchout** [comment]
![Uploading Screenshot 2022-03-07 at 16.30.06.png…]()

**Comment by Clem-mrtn** [comment]
- Mettre le "Découvrez.." en noir
- Rajouter les URL

**Comment by florianpanchout** [comment]
![Screenshot 2022-03-10 at 10 36 00](https://user-images.githubusercontent.com/8115933/157633645-1b0b0f9b-bd1a-4a01-ad83-08977976dd87.png)

**Comment by florianpanchout** [comment]
Est ce que ce ne serait pas plus logique de remonter "Découvrez nos outils de sensibilisation" au dessus de NGC ?

**Comment by Clem-mrtn** [comment]
Ca évite d'avoir trop de texte, l'un en dessous de l'autre de le positionner sous NGC

**Comment by Clem-mrtn** [comment]
On partirait là-dessus en terme de Kakémono : 
https://www.vistaprint.fr/pancartes-affiches/roll-ups?project_id=bdd25a27-c80b-48ae-b795-f261e9a0ad66&GP=03%2f10%2f2022+04%3a28%3a27&GPS=6191937610&GNF=1

**Roll-up 85x200 Premium** 
**Taille du document coupé
85,0 x 206,0 cm
2510 x 6083 pixels
Taille de l'impression marges pleines comprises
85,6 x 206,6 cm
2528 x 6100 pixels
Pour une impression optimale, votre fichier graphique devrait avoir les dimensions du document avec les marges pleines.**

**Comment by florianpanchout** [comment]
Le psd aux bonnes dimensions est ici : https://cloud.datagir.com/index.php/apps/files/?dir=/Datagir/Communication
