### ISSUE TITLE
Mettre à jour capture d'écran de MIT

### ISSUE THREAD

**Issue by martinregner** [datagir/datagir-site#89]
[datagir-site](https://github.com/datagir/datagir-site)/[content](https://github.com/datagir/datagir-site/tree/master/content)/[applications](https://github.com/datagir/datagir-site/tree/master/content/applications)/[mon-impact-transport](https://github.com/datagir/datagir-site/tree/master/content/applications/mon-impact-transport)/mon-impact-transport.png

**Comment by florianpanchout** [comment]
Done
